apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: uniflix.vip
  SECRET_ACME_EMAIL: solentankar@proton.me
  SECRET_CLOUDFLARE_TUNNEL_ID: 64368854-db82-408e-9b92-db90dae200ea
  SECRET_R2_HOST: https://8fdaa691408667c1914ee791977b10fe.r2.cloudflarestorage.com
  SECRET_EMAIL: mattias.m.svensson@gmail.com
  SECRET_USERNAME: mattias.m.svensson
  SECRET_TVSPORTSDB_DOMAIN: tvsportsdb.com
sops:
  age:
    - recipient: age1w9dv5enm6meku23cr82tfdgdmkqntrg0mnw5qyt7azyd59qvnc0q0xunp8
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBob0VaQldBNG4vOWFUR0ZD
        cFhjZHpmQnZwODJ2REVITGIrbDQvU29PVFZNClg3U0FHVG5kdU41YVlMNnVXbER1
        UFl3TDBSOTFGTm45L3hzMENvT2NxdUUKLS0tIGsrQ2pYY200VGxPYlNVSmpBbDU4
        MVZEdHMzdjdhVnVnNXdRQ0E1UVFpUVkKzKSs+WiFMPZIuJLCnfKnj6Nf/sPMpgMs
        IkK3p/pvnronfo6heRGZ0xeJHrouR5p7gavLfLkjq9uZ2hV7TiqNuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-16T10:53:27Z"
  mac: ENC[AES256_GCM,data:jB/CUS4Ffn0bIzFdJ2uvVpUWipXTwC1YUEBoelbmSSlRciO2w6sE+FNDYAyrzNzZ3cQpRX6wV2J55hQWHyNFlHr4uxEBeC64Wtc2zigT2yPb7+4qUNMDe7Hj0vrufYMhAb+NiKsy5nK6BGm3jL91VXKidCkbqBws/tza3Jocz4c=,iv:q2/GGlFvh4g85qEFVigtn300hii3nPh8PZo1mQg4tb8=,tag:yrhtxMLqMDKPAgNT3x6tFw==,type:str]
  encrypted_regex: ^(age.agekey|token|crt|key|id|secret|secretboxEncryptionSecret|ca)$
  mac_only_encrypted: true
  version: 3.11.0
