---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: solen-cluster
  TIMEZONE: "Europe/Stockholm"
  CLUSTER_CLOUDFLARE_TUNNEL_ID: 64368854-db82-408e-9b92-db90dae200ea
  TRUENAS_IP: 192.168.10.98
  K8S_GATEWAY_IP: 192.168.10.82
  NGINX_INTERNAL_IP: 192.168.10.81
  NGINX_EXTERNAL_IP: 192.168.10.83
  CLOUDNATIVE_PG_IP: 192.168.10.100
  PLEX_IP: 192.168.10.111
  UNIFI_IP: 192.168.10.112

  CLUSTER_CIDR: 10.69.0.0/16
  NODE_CIDR: 10.96.0.0/16
  WL_SOURCE_RANGE: 192.168.0.0/16,10.0.0.0/8
