---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./alertmanagerconfig.yaml
  - ./etcd-io-dashboard.yaml
  - ./etcd-io-dashboard-configmap.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./helmrepository.yaml
  - ./httproutes.yaml
