---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  # - ./komga/ks.yaml
  # - ./maintainerr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  # - ./podgrab/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sonarr/ks.yaml
  - ./sports-organizer/ks.yaml
  - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./unpackerr/ks.yaml
