---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./audiobookshelf/ks.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./maintainerr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./seasonpackarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sports-organizer/ks.yaml
  - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./unpackerr/ks.yaml
