---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: seerr-secret
    template:
      data:
        # Database configuration
        DB_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: &dbUser "{{ .SEERR_POSTGRES_USER }}"
        DB_PASS: &dbPass "{{ .SEERR_POSTGRES_PASS }}"
        DB_NAME: &dbName seerr

        # API Key
        API_KEY: "{{ .SEERR_API_KEY }}"

        # Database initialization (if needed)
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .CNPG_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
      rewrite:
        - regexp:
            source: "(.*)"
            target: "CNPG_$1"

    - extract:
        key: seerr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "SEERR_$1"

