---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextcloud
spec:
  hostnames:
    - "cloud.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    # Redirect well-known URLs for CalDAV/CardDAV
    - matches:
        - path:
            type: Exact
            value: /.well-known/carddav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301
    - matches:
        - path:
            type: Exact
            value: /.well-known/caldav
      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /remote.php/dav
            statusCode: 301
    # Redirect webfinger and nodeinfo
    - matches:
        - path:
            type: Exact
            value: /.well-known/webfinger
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.php/.well-known/webfinger
      backendRefs:
        - name: nextcloud
          port: 8080
    - matches:
        - path:
            type: Exact
            value: /.well-known/nodeinfo
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplaceFullPath
              replaceFullPath: /index.php/.well-known/nodeinfo
      backendRefs:
        - name: nextcloud
          port: 8080
    # Default route
    - backendRefs:
        - name: nextcloud
          port: 8080

