---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blueriiot2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: blueriiot2mqtt-secret
    template:
      data:
        BlueRiiot__Username: "{{ .BLUERIIOT_USER }}"
        BlueRiiot__Password: "{{ .BLUERIIOT_PASS }}"
  dataFrom:
    - extract:
        key: blueriiot2mqtt
      rewrite:
        - regexp:
            source: "(.*)"
            target: "BLUERIIOT_$1"
