---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./authelia/ks.yaml
  - ./blueriiot2mqtt/ks.yaml
  - ./glauth/ks.yaml
  - ./go2rtc/ks.yaml
  - ./home-assistant/ks.yaml
  - ./hortusfox-web/ks.yaml
  - ./mosquitto/ks.yaml
  - ./nextcloud/ks.yaml
  - ./thetvsportsdb/ks.yaml
  - ./zigbee/ks.yaml
