apiVersion: v1
kind: Endpoints
metadata:
  name: external-truenas
subsets:
  - addresses:
      - ip: 192.168.200.10
    ports:
      - port: 443
        name: https
---
apiVersion: v1
kind: Service
metadata:
  name: external-truenas
spec:
  ports:
    - port: 80
      targetPort: 443
      name: https
  clusterIP: None
  type: ClusterIP
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-truenas
  labels:
    auth.home.arpa/enabled: "true"
spec:
  hostnames:
    - "scale.${SECRET_DOMAIN}"
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: external-truenas
          port: 80
