---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: playbook
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: playbook-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_USER_KEY: "{{ .USER_KEY }}"
        PUSHOVER_API_TOKEN: "{{ .SPORTSORGANIZER_TOKEN }}"
        DISCORD_WEBHOOK_URL: "{{ .SPORTPULSE }}"
        PLEX_TOKEN: "{{ .PLEX_TOKEN }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: discord
    - extract:
        key: plex
      rewrite:
        - regexp:
            source: "(.*)"
            target: "PLEX_$1"
