apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kometa-trigger
  namespace: media
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kometa-trigger
  namespace: media
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kometa-trigger
subjects:
  - kind: ServiceAccount
    name: playbook
    namespace: media

