---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sports-organizer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: sports-organizer-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_USER_KEY: "{{ .USER_KEY }}"
        PUSHOVER_API_TOKEN: "{{ .SPORTSORGANIZER_TOKEN }}"
        DISCORD_WEBHOOK_URL: "{{ .SPORTPULSE }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: discord
