---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sports-organizer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sports-organizer-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_USER_KEY: "{{ .USER_KEY }}"
        PUSHOVER_API_TOKEN: "{{ .SPORTSORGANIZER_TOKEN }}"
  dataFrom:
    - extract:
        key: pushover
